In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('bmi_data.csv')
df.head(10)

Sex  Age  Height(Inches)  Weight(Pounds)        BMI
0  Female   21        65.78331        112.9925  18.357646
1  Female   35        71.51521        136.4873  18.762652
2  Female   27        69.39874        153.0269  22.338985
3    Male   24        68.21660        142.3354  21.504612
4  Female   18        67.78781        144.2971  22.077669
5  Female   22        68.69784        123.3024  18.368944
6    Male   35        69.80204        141.4947        NaN
7    Male   19        70.01472        136.4623  19.571891
8  Female   28        67.90265        112.3723  17.135021
9    Male   25        66.78236        120.6672  19.022366

In [3]:
df.isnull().sum()

Sex                0
Age                0
Height(Inches)    19
Weight(Pounds)    16
BMI               50
dtype: int64

In [4]:
df['Height(Inches)'] = df['Height(Inches)'].fillna(df['Height(Inches)'].mean())
df['Weight(Pounds)'] = df['Weight(Pounds)'].fillna(df['Weight(Pounds)'].mean())
df['BMI'] = df['BMI'].fillna(df['BMI'].mean())

In [5]:
df.isnull().sum()

Sex               0
Age               0
Height(Inches)    0
Weight(Pounds)    0
BMI               0
dtype: int64

In [6]:
df.drop('Sex', axis=1, inplace=True)
df.head(10)

Age  Height(Inches)  Weight(Pounds)        BMI
0   21        65.78331        112.9925  18.357646
1   35        71.51521        136.4873  18.762652
2   27        69.39874        153.0269  22.338985
3   24        68.21660        142.3354  21.504612
4   18        67.78781        144.2971  22.077669
5   22        68.69784        123.3024  18.368944
6   35        69.80204        141.4947  19.321368
7   19        70.01472        136.4623  19.571891
8   28        67.90265        112.3723  17.135021
9   25        66.78236        120.6672  19.022366

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
x = df.drop('BMI', axis=1)
y = df['BMI']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=51)
print(x_train.shape)
print(x_test.shape)

(20000, 3)
(5000, 3)


In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.fit_transform(x_test)
print(x_train_sc)
print(x_test_sc)

[[ 0.47926679  2.72967786  3.03055706]
 [-1.05931038 -0.29930059 -0.41870678]
 [-0.86698823 -2.00346988 -0.42574934]
 ...
 [ 1.44087751  0.14066694  1.85594568]
 [ 0.86391108 -0.23774983  0.20154588]
 [-0.86698823  0.50276714 -0.08430984]]
[[-0.09043917 -0.39916252 -0.74172636]
 [-1.44896747 -1.36806429 -0.83821278]
 [ 1.07401366 -0.0116154   0.5602289 ]
 ...
 [ 0.68586271  0.47772418 -0.57848411]
 [ 0.49178724  0.17394589 -1.34029544]
 [ 0.49178724 -1.093545   -0.09563589]]


In [57]:
from sklearn.linear_model import LinearRegression
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)
pred_lr = model_lr.predict(x_test)
pred_lr

array([18.41017023, 19.29282655, 20.32108086, ..., 17.74792401,
       16.71304843, 20.32314087])

In [61]:
pd.DataFrame({'actual': y_test, 'predicted': pred_lr, 'diff': (y_test - pred_lr)}).head(10)

actual  predicted      diff
21981  18.391304  18.410170 -0.018866
7093   19.262573  19.292827 -0.030253
14317  20.326478  20.321081  0.005397
1049   19.841424  19.870648 -0.029224
104    17.544549  17.553264 -0.008715
18231  20.226810  20.209625  0.017185
24198  18.350507  18.304466  0.046041
22395  17.973327  17.932664  0.040664
4578   15.353556  15.240550  0.113006
15072  19.196436  19.255968 -0.059532

In [62]:
import joblib
joblib.dump(model_lr, 'BMI-Prediction.pkl')

['BMI-Prediction.pkl']

In [63]:
model = joblib.load('BMI-Prediction.pkl')